language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors

before_install:
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran

install:
  - pip install pip --upgrade
  - pip install numpy
  - pip install nose
  - pip install coverage
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - nosetests --with-coverage

after_success::
  - coveralls
